config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

root to: "welcome#index"
resources :oils do
  resources :comments
end

resources :remedies do
  resources :remedy_comments
  
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :oil
  # For consistency, I would call this an `OilComment` because you have `RemedyComment`
end

app/models/oil.rb
class Oil < ActiveRecord::Base
  has_many :comments
  

end

app/models/remedy.rb
class Remedy < ActiveRecord::Base
has_many :remedy_comments

end

app/models/remedy_comment.rb
class RemedyComment < ActiveRecord::Base
  belongs_to :remedy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @oil = Oil.find(params[:oil_id])
    @comment = @oil.comments.create(comment_params)
    redirect_to oil_path(@oil)
  end

  def new
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.new
  end

  
  def edit
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to oil_path(@oil)
  end


  def show
    @oil =Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
  end



  def destroy
    @oil = Oil.find(params[:oil_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to oil_path(@oil)

  end


  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/oils_controller.rb
class OilsController < ApplicationController

  def index
    @oils = Oil.all

  end

  def edit
    @oil = Oil.find(params[:id])

  end

  def update
    @oil = Oil.find(params[:id])
    @oil.update(oil_params)
    redirect_to @oil
  end


  def create
    @oil  = Oil.new(oil_params)
    if @oil.save
      redirect_to @oil
    else
      render 'new'
    end
  end

  def show
    @oil =Oil.find(params[:id])
  end

  def new
    @oil = Oil.new
  end

  def destroy
    @oil = Oil.find(params[:id])
    @oil.destroy

    redirect_to oils_path
  end

  private
  def oil_params
    params.require(:oil).permit(:name, :photo_url, :benefits, :descriptions, :uses, :directions, :cautions)
  end


end

app/controllers/olis_controller.rb
class OilsController < ApplicationController

  def index
    @oils = Oil.all
    render :index

  end


  def create
    @oil  = Oil.create!(oil_params)
    redirect_to "/oils/#{{@oil.id}}"
  end


  private
  def oil_params
    params.require(:oil).permit(:name, :photo_url, :benefits)
  end






end

app/controllers/remedies_controller.rb
class RemediesController < ApplicationController

  def index
    @remedies = Remedy.all

  end

  def edit
    @remedy = Remedy.find(params[:id])
  end

  def create
    @remedy = Remedy.new(remedy_params)
    if @remedy.save
      redirect_to @remedy
    else
      render 'new'
    end
  end

  def show
    @remedy = Remedy.find(params[:id])
  end

  def update
    @remedy = Remedy.find(params[:id])
    @remedy.update(remedy_params)
    redirect_to @remedy
  end


  def new
    @remedy = Remedy.new
  end

  def destroy
    @remedy = Remedy.find(params[:id])
    @remedy.destroy

    redirect_to remedies_path
  end

  private
  def remedy_params
    params.require(:remedy).permit(:name, :video_url, :benefits, :directions)
  end


end

app/controllers/remedy_comments_controller.rb
class RemedyCommentsController < ApplicationController

  def create
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = @remedy.remedy_comments.create(comment_params)
    redirect_to remedy_path(@remedy)
  end

  def show
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = RemedyComment.find(params[:id])
  end


  def new
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = RemedyComment.new
  end


  def edit
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = @remedy.remedy_comments.find(params[:id])
  end

  def update
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = RemedyComment.find(params[:id])
    @remedy_comment.update(comment_params)
    redirect_to remedy_path(@remedy)
  end

  def destroy
    @remedy = Remedy.find(params[:remedy_id])
    @remedy_comment = RemedyComment.find(params[:id])
    @remedy_comment.destroy
    redirect_to remedy_path(@remedy)

  end

  private
  def comment_params
    params.require(:remedy_comment).permit(:name, :comment)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/remedies_helper.rb
module RemediesHelper
end

app/helpers/remedy_comments_helper.rb
module RemedyCommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<h3>Edit a comment:</h3>
<%= form_for([@oil, @comment]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :commenter %>
</p>
<p>
  <%= f.label :said %><br>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OilsRemedies</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Raleway">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-default">
        <div class="container">
          <%= link_to "Oils and Remedies", '#', id: "logo" %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home",   welcome_index_path %></li>
              <li><%= link_to "Essential Oils",  oils_path %></li>
              <li><%= link_to "Remedies", remedies_path %></li>
            </ul>
          </nav>
        </div>
      </header>


  <!-- <div class = "menubar">
    <div class="links">
      <div class = "mainclick homebutton"><%= link_to 'Home', welcome_index_path %></div>
      <div class = "mainclick oilbar"><%= link_to 'Essential Oils', oils_path %></div>
      <div class = "mainclick"><%= link_to 'Remedies', remedies_path %></div>
    </div>
  </div> -->



  <%= yield %>

  <footer>
    <p>Woo Yun, 2016 @ All rights reserved.</p>
  </footer>
</body>
</html>

app/views/oils/_form.html.erb
<%= form_for @oil do |f| %>

  <% if @oil.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@oil.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @oil.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :photo_url %><br>
    <%= f.text_field  :photo_url %>
  </p>

  <p>
    <%= f.label :benefits %><br>
    <%= f.text_area :benefits %>
  </p>

  <p>
    <%= f.submit %>
  </p>

 <% end %>

 <%= link_to 'Back', oils_path %>

app/views/oils/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

app/views/oils/index.html.erb
<h1>Essential Oils<h1>
<div class = "oillist">
  <% @oils.each do |oil| %>
      <div class="oil">
        <%= link_to image_tag(oil.photo_url), oil_path(oil) %>
      </div>
      <!-- <%= link_to oil.name, oil_path(oil) %> -->
  <% end %>
</div>
  <h2><%= link_to "Add Oil", new_oil_path %></h2>

app/views/oils/new.html.erb
<h1>Add New Oil</h1>

<%= render 'form' %>

app/views/oils/show.html.erb
<h1><%= @oil.name %></h1>

<p>

  <!-- <strong>Image:</strong> -->
  <%= image_tag @oil.photo_url %>
  <ul class = "oil-discription">
    <li>
      <h2>Benefits:</h2>
    <h3><%= @oil.benefits %></h3>
    </li>
    <li>
      <h2>Decriptions:</h2>
      <h3><%= @oil.descriptions %></h3>
    </li>
    <li>
      <h2>Uses:</h2>
      <h3><%= @oil.uses %></h3>
    </li>
    <li>
      <h2>Direction:</h2>
      <h3><%= @oil.directions %></h3>
    </li>
    <li>
      <h2>Cautions:</h2>
      <h3><%= @oil.cautions %></h3>
    </li>
  </ul>



</p>



<h3>Comments</h3>
<% @oil.comments.each do |comment| %>
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Said:</strong>
  <%= comment.body %>
</p>

<%= link_to "Edit", edit_oil_comment_path(@oil, comment) %> |
<%= link_to "Delete", oil_comment_path(@oil, comment), method: :delete %>

<% end %>


<h3>Add a comment:</h3>
<%= form_for([@oil, @oil.comments.build]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :commenter %>
</p>
<p>
  <%= f.label :said %><br>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Delete', oil_path(@oil),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_oil_path(@oil) %>
<%= link_to 'Back', oils_path %>

app/views/olis/index.html.erb
<h1>Essential Oils<%= link_to "Add Oil", new_oil_path %><h1>

<ul>
  <% oils.each do |oil| %>
    <li>
      <a href="/oils/<%=  oil.id %>">
      <%= oil.name %>
      </a>
    </li>
  <% end %>
</ul>

<!-- This folder isn't being used since `olis` was misspelled. Make sure to clean up unused code. -->

app/views/remedies/_form.html.erb
<%= form_for @remedy do |f| %>

  <% if @remedy.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@remedy.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @remedy.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :video_url %><br>
    <%= f.text_field  :video_url %>
  </p>

  <p>
    <%= f.label :benefits %><br>
    <%= f.text_area :benefits %>
  </p>

  <p>
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </p>



  <p>
    <%= f.submit %>
  </p>

 <% end %>

 <%= link_to 'Back', remedies_path %>

app/views/remedies/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

<%= link_to 'Back', remedies_path %>

app/views/remedies/index.html.erb
<h1>Remedies</h1>

<table>
  <% @remedies.each do |remedy| %>
    <div class = "remedylist">
      <div class = "center_remedy">
        <div class="remedy"><%= link_to remedy.name, remedy_path(remedy) %></div>
      </div>

    </div>


  <% end %>
</table>

<h2><%= link_to "Add Remedy", new_remedy_path %>

app/views/remedies/new.html.erb
<h2>Add New Remedy</h2>

<%= render 'form' %>

<%= link_to 'Back', remedies_path %>

app/views/remedies/show.html.erb
<h1><%= @remedy.name %></h1>

<!-- <%= link_to 'Back', remedies_path %> -->
<ul>
<iframe width="560" height="315" src="<%=@remedy.video_url%>" frameborder="0" allowfullscreen></iframe>
</ul>

<h3>Comments</h3>
<% @remedy.remedy_comments.each do |comment| %>
<li>
  <strong>Name:</strong>
  <%= comment.name %>

  <strong>Said:</strong>
  <%= comment.comment %>
</li>

<%= link_to "Edit", edit_remedy_remedy_comment_path(@remedy, comment) %> |
<%= link_to "Delete", remedy_remedy_comment_path(@remedy, comment), method: :delete %>

<% end %>



<h3>Add a comment:</h3>
<%= form_for([@remedy, @remedy.remedy_comments.build]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :comment %><br>
  <%= f.text_area :comment %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Delete', remedy_path(@remedy),
method: :delete,
data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_remedy_path(@remedy) %>

app/views/remedy_comments/edit.html.erb
<h3>Add a comment:</h3>
<%= form_for([@remedy, @remedy_comment]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Oils and Remedies<h1>


  <div id="container">

    <!-- <%= image_tag "arrow-left.png", alt: "Prev", id: "prev" %> -->
    <div id="slider" align="center">
      <div class="slide">
        <%= image_tag "slide1.jpg" %>
        <div class="slide-copy">
          <p>For people who care about improving their health and their loved ones, we provide simple, safe, and empowersing solutions that enhance well-being.</p>
        </div>
      </div>

      <div class="slide">
        <div class="slide-copy">

          <p>Our pure essential oils are revolutionizing the way families manage their health. We harness nature's most powerful elements and share these gifts through our global community of Wellness Advocates.</p>
        </div>
        <%= image_tag "slide2.jpg" %>
      </div>

      <div class="slide">
        <div class="slide-copy">
          <p>Our Healing Hands Foundation seeks to bring healing and hope to the world as we work to make possible lives free of disease and poverty, ultimately teaching people everywhere to be self reliant.</p>
        </div>
        <%= image_tag "slide3.jpg" %>
      </div>
    </div>
    <!-- <%= image_tag "arrow-right.png", alt: "Next", id: "next" %> -->
  </div>
  <div style="clear:both"></div>
  <div class="video-box">
    <h1>What is a doTERRA Essential Oil?</h1>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/OEnKOk4ad0U" frameborder="0" allowfullscreen></iframe>
  </div>
  <!-- <div class="video-box">
  <h2>Why You Should Choose doTERRA Essential Oils</h2>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/o_M4XsYaOxM" frameborder="0" allowfullscreen></iframe>
</div> -->